ALTER TABLE TURMA ADD CONSTRAINT PK_CO_TURMA PRIMARY KEY (CO_TURMA);

ALTER TABLE CURSO ADD CONSTRAINT PK_CO_CURSO PRIMARY KEY (CO_CURSO);

ALTER TABLE TURMA ADD CONSTRAINT FK_TURMA_CO_CURSO FOREIGN KEY (CO_CURSO) REFERENCES CURSO(CO_CURSO);

ALTER TABLE ALUNO ADD CONSTRAINT PK_CO_ALUNO PRIMARY KEY (CO_ALUNO);

ALTER TABLE PROVA ADD CONSTRAINT PK_CO_PROVA PRIMARY KEY (CO_PROVA);

ALTER TABLE PROFESSOR ADD CONSTRAINT PK_CO_PROFESSOR PRIMARY KEY (CO_PROFESSOR);

ALTER TABLE ALUNO_TURMA ADD CONSTRAINT PK_ALUNO_TURMA PRIMARY KEY (CO_ALUNO, CO_TURMA);

ALTER TABLE ALUNO_TURMA ADD CONSTRAINT FK_ALUNO_TURMA_CO_ALUNO FOREIGN KEY (CO_ALUNO) REFERENCES ALUNO(CO_ALUNO);

ALTER TABLE ALUNO_TURMA ADD CONSTRAINT FK_ALUNO_TURMA_CO_TURMA FOREIGN KEY (CO_TURMA) REFERENCES TURMA(CO_TURMA);

ALTER TABLE DISCIPLINA ADD CONSTRAINT PK_CO_DISCIPLINA PRIMARY KEY (CO_DISCIPLINA);

ALTER TABLE FREQUENCIA ADD CONSTRAINT PK_FREQUENCIA PRIMARY KEY (CO_ALUNO, CO_TURMA, CO_DISCIPLINA, DT_FREQUENCIA);

ALTER TABLE FREQUENCIA ADD CONSTRAINT FK_FREQUENCIA_CO_ALUNO_CO_TURMA FOREIGN KEY (CO_ALUNO, CO_TURMA) REFERENCES ALUNO_TURMA(CO_ALUNO, CO_TURMA);

ALTER TABLE FREQUENCIA ADD CONSTRAINT FK_FREQUENCIA_CO_DISCIPLINA FOREIGN KEY (CO_DISCIPLINA) REFERENCES DISCIPLINA(CO_DISCIPLINA);

ALTER TABLE AVALIACAO ADD CONSTRAINT PK_AVALIACAO PRIMARY KEY (CO_ALUNO, CO_TURMA, CO_DISCIPLINA, CO_PROVA);

ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_CO_ALUNO_CO_TURMA FOREIGN KEY (CO_ALUNO, CO_TURMA) REFERENCES ALUNO_TURMA(CO_ALUNO, CO_TURMA);

ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_CO_DISCIPLINA FOREIGN KEY (CO_DISCIPLINA) REFERENCES DISCIPLINA(CO_DISCIPLINA);

ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_CO_PROVA FOREIGN KEY (CO_PROVA) REFERENCES PROVA(CO_PROVA);

ALTER TABLE PROF_TURM_DISC ADD CONSTRAINT PK_PROF_TURM_DISC PRIMARY KEY (CO_PROFESSOR, CO_TURMA, CO_DISCIPLINA);

ALTER TABLE PROF_TURM_DISC ADD CONSTRAINT FK_PROF_TURM_DISC_CO_PROFESSOR FOREIGN KEY (CO_PROFESSOR) REFERENCES PROFESSOR(CO_PROFESSOR);

ALTER TABLE PROF_TURM_DISC ADD CONSTRAINT FK_PROF_TURM_DISC_CO_TURMA FOREIGN KEY (CO_TURMA) REFERENCES TURMA(CO_TURMA);

ALTER TABLE PROF_TURM_DISC ADD CONSTRAINT FK_PROF_TURM_DISC_CO_DISCIPLINA FOREIGN KEY (CO_DISCIPLINA) REFERENCES DISCIPLINA(CO_DISCIPLINA);
